language: rust
rust:
  - 1.36.0

cache: cargo

branches:
  only:
    - master

before_script:
  - rustup component add clippy rustfmt

matrix:
  include:

    - os: osx
      script:
        - cargo clippy --features metal -- -D warnings
        - cargo fmt -- --check
        - cargo test --verbose --features metal

    - os: windows
      before_install:
        - choco install -y ninja python cmake
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script:
        - cargo clippy --features vulkan -- -D warnings
        - cargo fmt -- --check
        - cargo test --verbose --features vulkan

    - os: linux
      script:
        - cargo clippy --features vulkan -- -D warnings
        - cargo fmt -- --check
        - cargo test --verbose --features vulkan
