[package]
name = "hurban_selector"
version = "0.1.0"
edition = "2018"

authors = [
    "Ondrej Slinták <ondrowan@gmail.com>",
    "Ján Tóth <yanchi.toth@gmail.com>",
    "Ján Pernecký <info@sub.digital>",
]
license = "GPL-3.0-only"

# This has to be done using features since target dependent compilation is
# currently broken in Cargo: https://github.com/rust-lang/cargo/issues/2524
[features]
d3d11 = ["wgpu/dx11"]
d3d12 = ["wgpu/dx12"]
metal = ["wgpu/metal"]
vulkan = ["wgpu/vulkan"]

# Currently disabled. Not very stable yet and requires an explicit
# init code path, might want to enable later.
# opengl = ["wgpu/gl"]

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "79b5342ee2972b219e1ba08173b4d6c88b191344" }
imgui = "0.1.0"
imgui-winit-support = "0.1.0"
tinyfiledialogs = "3.3.5"
tobj = "0.1.8"
crc32fast = "1.2.0"
log = "0.4.7"
nalgebra = "0.18.0"
env_logger = "0.6.2"
png = "0.15.0"
crossbeam-channel = "0.3.9"
bitflags = "1.1.0"
approx = "0.3.2"

[build-dependencies]
shaderc = "0.6.0"
