[package]
name = "hurban_selector"
version = "0.1.0"
authors = [
    "Ondrej Slinták <ondrowan@gmail.com>",
    "Ján Tóth <yanchi.toth@gmail.com>",
    "Ján Pernecký <info@sub.digital>",
]
edition = "2018"

# This has to be done using features since target dependent compilation is
# currently broken in Cargo: https://github.com/rust-lang/cargo/issues/2524
[features]
metal = ["wgpu/metal"]
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = "0.2.3"
imgui = "0.1.0"
imgui-winit-support = "0.1.0"
shaderc = "0.6.0"
tinyfiledialogs = "3.3.5"
tobj = "0.1.8"
